# 개발 환경에서 사용하는 docker-compose.yml 파일 (Local 개발)
# 코드 변경이 많을 때 (hot reload 필요)
version: '3.8'

services:
  ccb-ai:
    # 개발 환경에서는 소스 코드를 마운트하여 실시간 변경 반영
    volumes:
      - .:/app
      - ./output:/app/output
      - ./logs:/app/logs
      # 개발 환경에서는 raw 데이터 제외 (VectorDB만 사용)
      - /app/chatbot/data/raw
      - /app/chatbot/data/processed
      - /app/chatbot/data/results
    environment:
      - APP_ENV=development
      - PYTHONPATH=/app
      # LangSmith Tracing 환경 변수 추가
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    # 개발 모드로 실행 (--reload 옵션 추가) - 통합 서버 사용
    command: ["uvicorn", "chatbot.app:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    
  # 개발 환경에서는 Nginx 제외
  nginx:
    profiles:
      - production

  # 개발용 추가 서비스들
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: ccb-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - ccb-network
    profiles:
      - dev-tools 